import NavBar from '@/components/nav-bar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { exo2, orbitron } from './fonts';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${orbitron.variable} ${exo2.variable}`}
    >
      <body className='bg-orange-50 flex flex-col px-4 py-2 min-h-screen'>
        <header>
          <NavBar />
        </header>
        <main className='grow py-3'>{children}</main>
        <footer className='border-t py-3 text-center text-sx'>
          Game data and images courtesy of{' '}
          <a
            href='https://rawg.io/'
            target='_blank'
            className='text-orange-800 hover:underline'
          >
            RAWG
          </a>
        </footer>
      </body>
    </html>
  );
}
